# This is a basic workflow to help you get started with Actions

name: Testing Site

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2  
     
      - name: Setup Node
        uses: actions/setup-node@v2  
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
        with:
          node-version: '20'
          cache: 'npm'   
      
      - name: Navigate to FrontEnd/MainDex and Install Packages
        run: |
          cd FRONTEND/MAINDEX
          npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}    
      
      - name: Build Project
        run: |
          cd FRONTEND/MAINDEX
          npm run build
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.solforgeai.com
          username: deploy@solforgeai.com
          password: Deploy2025.
          protocol: ftps
          port: 21
          local-dir: ./FRONTEND/MAINDEX/dist/
          server-dir: /testing.solforgeai.com/
          state-name: /testingSite.json	
